= Changles
:toc: left

== 0.0.3
    - [x] disable ImGui Win32 backend update mouse pos
    - [x] auto hide tool window when lost focus
        ** [x] when window focused/Activate/restore mark `ShouldResetKeyboard` as ture
    - [x] try fix log source location
        ** https://github.com/gabime/spdlog/issues/1959
    - [x] imgui cursor dead
    - [x] use detours hook DirectInputDevice.
    - [x] remove/hide reset keyboard state button(need auto reset keyboard state)
        ** [x] fix: when tool window is pined, any mouse click(out of window?) will
         make tool window immediate lost foucs after next unpin
    - [x] Add ui color config;
    - [ ] check memory overflow;
    - [x] try convert candidate imm api to tsf candidate api

== 0.0.4
    - [x] open janpaniese ime & close game will crash
        ** Check `RE::InterfaceStrings`, `RE::MessageDataFactoryManager` is nullptr
    - [x] Modex crash with ImGuiIO::ClearInputKeys
        ** [x] Delay `SetFoucs` call to avoid some mod call ImGui when their ImGui context not created yet.Modex
    - [x] activate ime function must be call in message loop thread.
    - [x] launch ImeWnd,ImeUi in standalone thread to and use ourself message loop
         avoid other plugin init COM with `COINIT_MULTITHREADED`(crash logger)

== 0.0.5
    - [x] try use macro define AppConfig property;
    - [x] re-organize config header
    - [x] optimize Property class;
        ** [x] back to SimpleINI? test is support read config like 0xFF00FF00 style
    - [x] enable test & integration googletest
    - [x] check SEH expression can be capture crash exception?
        - can only capture this plugin crash error
    - [x] crash with candidate list
    - [x] WcharBuf optimize
        - [x] Test WcharBuf
    - [x] fix candidate update when ime is Microsoft PinYin
        ** [x] check if IME support TSF, switch to TSF UI to replace candidate list read.
    - [x] switch TSF/Imm32 by config;
    - [.line-through]#[ ] render sentence?(may GoogleJapanese need)# not sentence
    - [x] fix selection
    - [x] crashed when comp & candidate ui not close to load game; Disable event discard in loading game.
    - [x] update cursor pos when game cursor hide;
    - [x] disable IME when launch game(avoid loss input on some input method)

== 0.0.6

* [ ] Dynamic enable/disable IME
** [x] Disable when no any menu open;
** [ ] Disable by blacklist, we can ensure what menu not support input
*** bug when: curosor -> menu1(IME enable) -> menu2(IME disable) -> menu2 close -> menu1(error state, IME closed)
** iterate menu stack to find first context-id is not 19 (commonlib-ng kNone = 18?)
*** No, SkyrUi support search in inventory menu but context is kNone

[source,c++]
----
auto *ui      = RE::UI::GetSingleton();
using Context = RE::UserEvents::INPUT_CONTEXT_IDS;
log_debug("menu {}, open {}", a_event->menuName.c_str(), a_event->opening);
log_debug("stack {}", ui->menuStack.size());
auto hasInputContext = false;
for (const auto &menu : ui->menuStack)
{
    auto menuName = std::string(typeid(*menu.get()).name());
    menuName.erase(0, strlen("class "));
    log_debug(
        "  menu name {} context {} {:32b}", menuName,
        static_cast<uint32_t>(menu->inputContext.get()), static_cast<uint32_t>(menu->menuFlags.get()));
    // SE kNone = 18, AE kNone = 19
    // TODO can't dynamic activate IME by check inputContext: InventoryMenu(SkyUi) no inpuContext
    if (menu->inputContext.get() != 19 && !IsMenuDisableIme(menuName))
    {
        log_debug("=====Has Input Context");
        hasInputContext = true;
        break;
    }
}
----


=== Improvement

* [x] Enable when cursor visible(All text field show show cursor);

== 0.0.7

=== Issues

* [ ] `SteamOverlay` can't receive any keyboard input

Reason:

** Mod always forward focus to ImeWnd, `SteamOverlay` work in Skyrim depends on message loop

Solutions:

* [.line-through]#try HWND_MESSAGE#
* [.line-through]#send all message or only IME & Key message#
** The context state inconsistency
* listen SteamOverlay shortcut(need user config himself SteamOverlay shortcut)

* Only forward key up/down & SysKeyUp/Down message
* new UI checkbox: if checked,
** disable all mod feature and restore focus to game main window.
** reset DirectInputDevice keyboard to exclusive mode

* [ ] `TextEntryCount`. Open Map `find location` menu and press `ESC` will to quit will not trigger 
`AllowTextInput` with false

=== Improvement

* [x] Can disable mod
* [x] update discard event logic
    . not discard when modifier key down: alt/shift/win/ctrl
* [x] Enable when menu open that contain some textfield;
    . Hook AllowInputText(logic follow SKSE `Hooks_Scaleform.cpp#SKSEScaleform_AllowTextInput`)
* [x] Abort IME composition if comp window(ImGui) lost focus
    . Focus parent window to abort IME(then automatic focus to ImeWnd)
* [x] Support make composition and candidate window follow cursor when first appear.

== 0.0.8

* [x] Settings window;
* [x] FMOD
    . check if install RaceSexMenu patch
* [x] ImGui Theme load from file
    . theme file export from https://github.com/Patitotective/ImThemes[ImThemes]
    . theme no provide text link color, try another way to show selected text(add background?)
* [x] keepimeopen <--- always enable ime
    . Depreated config `Always_Enable_Ime`;
* [ ] scale & add bg from selected candidate

=== fix

* [x] discard `E` key event when ime in input or wait input
* [x] ImGui cursor not update when keep any key pressed
. Always update ImGui cursor pos in `ImeWnd#NewFrame`
* [x] detach, uninstall hooks when destory window
* [x] TextEntry can't input english
    . Our override SKSE `AllowTextInput` gfx function. And SKSE modify member `allowTextInput` 
in `RE::ControlMap` offset 128. We need sync it.
    . Can we trampline SKSE `AllowTextInput` gfx function?

== 0.1.0

=== Issues

* [x] In some case, game & ime will lost keyboard input at same time.
** Refactor Focus & `IME_DISABLED` state manage. Now, no longer associate empty document to tsf.
Just restore focus to game window. 
*** Ime enable -> Focus to `ImeWnd`
*** Ime disable -> Focus to Game window
* [ ] In some case, TSF may not recived the shift key up event? Can't switch english & chinese mode.
** If checked `Keep Ime Open` and use `shift` to switch to english mode, TSF never recived shift key up/down event again.

* IME and TSF work at same times and TSF can't get composition string
** ❌ Because IME disabled in Game WndProc? No
** ✅ Because TextService `OnFocus` call? Yes, `onFocus` not call in message `WM_SETFOCUS` 

TSF focus when `CooperativeLevel` changed
** We should first change `CooperativeLevel`, then change focus?
** `win+Tab` switch window can fix TSF. may we clear `IME_DISABLED` and Focus game window -> Focus Ime?
** Try `AttachThreadInput`

=== improvment

* [x] No longer forward keyboard event to game main window.
** Because we have changed Focus & `IME_DISABLED` state manage logic. But we notify user close any text entry when open
Steam overlay.
* [x] Support mutiple language, default english and chinese
* [x] Refactor IME focus manage

== 0.1.1

* [x] `KreatE` Issue: Can't open
** Is `KreatE` depend `WM_KEYUP`, `WM_KEYDOWN` message?

== 0.2.0

* [x] Implement two style ImeManager
+
--
** `PermanentFocusManager`: completely grab game focus:
*** unlock/restore keyboard when MOD enable/disable
*** Change focus when IME enable/disable
** `SafeImeManager`
*** more *combatibility*. 
*** Change focus when IME enable/disable
*** unlock/restore keyboard when IME enable/disable
** Default use `PermanentFocusManager`
--

=== Issues

* [ ] `Keep Ime Open`: fix IME state inconsistency
* [ ] when use `TemporaryFocusImeManager`, press any character key when IME active, will trigger `kTilde`(~) key event.
+
Just giveup this feature?

== To-Do

=== Code improve

* [ ] ImeManager 
. for enable/disable mod, enable/disbale IME

* [ ] AppConfig
    - [ ] section;
    - [x] add new key by register;
    - universal config name style

=== Feature improve

* [ ] Support select candidate by mouse click
* [ ] Mod Error hint
* [ ] Ctrl-c/v support
    . In `DispatchInputEvent` detect copy command and transfer clipboard data to `TextService`
to disable game paste feature
* [ ] Support config `follow cursor` in `ini` file.
* [ ] support change and save configs in `ToolWindow`
* [ ] GameProfileSwitch script optimize;
* [ ] Manage GFXEvent memory alloc?
* [ ] scale or change ImGui cursor
* [ ] `CompassNavigationOverhaul` exception when quit game. Survey is trigger by our mod.
    . May related to AllowTextInput hook. Test SkyrimInputMethod with compass is crash
